export const LOCAL_FONTS = [
  "Agency FB",
  "Agency FB Bold",
  "Algerian",
  "AniMe Vision - MB_EN",
  "Arial",
  "Arial Black",
  "Arial Bold",
  "Arial Bold Italic",
  "Arial Italic",
  "Arial Narrow",
  "Arial Narrow Bold",
  "Arial Narrow Bold Italic",
  "Arial Narrow Italic",
  "Arial Rounded MT Bold",
  "Bahnschrift",
  "Baskerville Old Face",
  "Bauhaus 93",
  "Bell MT",
  "Bell MT Bold",
  "Bell MT Italic",
  "Berlin Sans FB",
  "Berlin Sans FB Bold",
  "Berlin Sans FB Demi Bold",
  "Bernard MT Condensed",
  "BIZ UDGothic",
  "BIZ UDGothic Bold",
  "BIZ UDMincho Medium",
  "BIZ UDPGothic (TrueType)",
  "BIZ UDPGothic Bold (TrueType)",
  "BIZ UDPMincho Medium (TrueType)",
  "Blackadder ITC",
  "Bodoni MT",
  "Bodoni MT Black",
  "Bodoni MT Black Italic",
  "Bodoni MT Bold",
  "Bodoni MT Bold Italic",
  "Bodoni MT Condensed",
  "Bodoni MT Condensed Bold",
  "Bodoni MT Condensed Bold Italic",
  "Bodoni MT Condensed Italic",
  "Bodoni MT Italic",
  "Bodoni MT Poster Compressed",
  "Book Antiqua",
  "Book Antiqua Bold",
  "Book Antiqua Bold Italic",
  "Book Antiqua Italic",
  "Bookman Old Style",
  "Bookman Old Style Bold",
  "Bookman Old Style Bold Italic",
  "Bookman Old Style Italic",
  "Bookshelf Symbol 7",
  "Bradley Hand ITC",
  "Britannic Bold",
  "Broadway",
  "Brush Script MT Italic",
  "Calibri",
  "Calibri Bold",
  "Calibri Bold Italic",
  "Calibri Italic",
  "Calibri Light",
  "Calibri Light Italic",
  "Californian FB",
  "Californian FB Bold",
  "Californian FB Italic",
  "Calisto MT",
  "Calisto MT Bold",
  "Calisto MT Bold Italic",
  "Calisto MT Italic",
  "Cambria",
  "Cambria Bold",
  "Cambria Bold Italic",
  "Cambria Italic",
  "Cambria Math",
  "Candara",
  "Candara Bold",
  "Candara Bold Italic",
  "Candara Italic",
  "Candara Light",
  "Candara Light Italic",
  "Cascadia Code Regular",
  "Cascadia Mono Regular",
  "Castellar",
  "Centaur",
  "Century",
  "Century Gothic",
  "Century Gothic Bold",
  "Century Gothic Bold Italic",
  "Century Gothic Italic",
  "Century Schoolbook",
  "Century Schoolbook Bold",
  "Century Schoolbook Bold Italic",
  "Century Schoolbook Italic",
  "Chiller",
  "Colonna MT",
  "Comic Sans MS",
  "Comic Sans MS Bold",
  "Comic Sans MS Bold Italic",
  "Comic Sans MS Italic",
  "Consolas",
  "Consolas Bold",
  "Consolas Bold Italic",
  "Consolas Italic",
  "Constantia",
  "Constantia Bold",
  "Constantia Bold Italic",
  "Constantia Italic",
  "Cooper Black",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Corbel",
  "Corbel Bold",
  "Corbel Bold Italic",
  "Corbel Italic",
  "Corbel Light",
  "Corbel Light Italic",
  "Courier 10,12,15",
  "Courier New",
  "Courier New Bold",
  "Courier New Bold Italic",
  "Courier New Italic",
  "Curlz MT",
  "DejaVu Math TeX Gyre",
  "DengXian",
  "DengXian Bold",
  "DengXian Light",
  "Dubai Bold",
  "Dubai Light",
  "Dubai Medium",
  "Dubai Regular",
  "Ebrima",
  "Ebrima Bold",
  "Edwardian Script ITC",
  "Elephant",
  "Elephant Italic",
  "Engravers MT",
  "Eras Bold ITC",
  "Eras Demi ITC",
  "Eras Light ITC",
  "Eras Medium ITC",
  "FangSong",
  "Felix Titling",
  "Footlight MT Light",
  "Forte",
  "Franklin Gothic Book",
  "Franklin Gothic Book Italic",
  "Franklin Gothic Demi",
  "Franklin Gothic Demi Cond",
  "Franklin Gothic Demi Italic",
  "Franklin Gothic Heavy",
  "Franklin Gothic Heavy Italic",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Cond",
  "Franklin Gothic Medium Italic",
  "Freestyle Script",
  "French Script MT",
  "Gabriola",
  "Gadugi",
  "Gadugi Bold",
  "Garamond",
  "Garamond Bold",
  "Garamond Italic",
  "Georgia",
  "Georgia Bold",
  "Georgia Bold Italic",
  "Georgia Italic",
  "Gigi",
  "Gill Sans MT",
  "Gill Sans MT Bold",
  "Gill Sans MT Bold Italic",
  "Gill Sans MT Condensed",
  "Gill Sans MT Ext Condensed Bold",
  "Gill Sans MT Italic",
  "Gill Sans Ultra Bold",
  "Gill Sans Ultra Bold Condensed",
  "Gloucester MT Extra Condensed",
  "Goudy Old Style",
  "Goudy Old Style Bold",
  "Goudy Old Style Italic",
  "Goudy Stout",
  "Haettenschweiler",
  "Harlow Solid Italic",
  "Harrington",
  "High Tower Text",
  "High Tower Text Italic",
  "Impact",
  "Imprint MT Shadow",
  "Informal Roman",
  "Ink Free",
  "Javanese Text",
  "Jokerman",
  "Juice ITC",
  "KaiTi",
  "Kingsoft UE",
  "Kristen ITC",
  "Kunstler Script",
  "Lato",
  "Lato Bold",
  "Lato BoldItalic",
  "Lato Italic",
  "Lato Light",
  "Lato LightItalic",
  "Lato Semibold",
  "Lato SemiboldItalic",
  "Leelawadee",
  "Leelawadee Bold",
  "Leelawadee UI",
  "Leelawadee UI Bold",
  "Leelawadee UI Semilight",
  "Lucida Bright",
  "Lucida Bright Demibold",
  "Lucida Bright Demibold Italic",
  "Lucida Bright Italic",
  "Lucida Calligraphy Italic",
  "Lucida Console",
  "Lucida Fax Demibold",
  "Lucida Fax Demibold Italic",
  "Lucida Fax Italic",
  "Lucida Fax Regular",
  "Lucida Handwriting Italic",
  "Lucida Sans Demibold Italic",
  "Lucida Sans Demibold Roman",
  "Lucida Sans Italic",
  "Lucida Sans Regular",
  "Lucida Sans Typewriter Bold",
  "Lucida Sans Typewriter Bold Oblique",
  "Lucida Sans Typewriter Oblique",
  "Lucida Sans Typewriter Regular",
  "Lucida Sans Unicode",
  "Magneto Bold",
  "Maiandra GD",
  "Malgun Gothic",
  "Malgun Gothic Bold",
  "Malgun Gothic SemiLight",
  "Matura MT Script Capitals",
  "Meiryo",
  "Meiryo Bold",
  "Meiryo Bold Italic",
  "Meiryo Italic",
  "Meiryo UI",
  "Meiryo UI Bold",
  "Meiryo UI Bold Italic",
  "Meiryo UI Italic",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei Bold",
  "Microsoft JhengHei Light",
  "Microsoft JhengHei UI",
  "Microsoft JhengHei UI Bold",
  "Microsoft JhengHei UI Light",
  "Microsoft New Tai Lue",
  "Microsoft New Tai Lue Bold",
  "Microsoft PhagsPa",
  "Microsoft PhagsPa Bold",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Tai Le Bold",
  "Microsoft Uighur",
  "Microsoft Uighur Bold",
  "Microsoft YaHei",
  "Microsoft YaHei Bold",
  "Microsoft YaHei Light",
  "Microsoft YaHei UI",
  "Microsoft YaHei UI Bold",
  "Microsoft YaHei UI Light",
  "Microsoft Yi Baiti",
  "MingLiU_HKSCS-ExtB",
  "MingLiU-ExtB",
  "Mistral",
  "Modern",
  "Modern No. 20",
  "Mongolian Baiti",
  "Monotype Corsiva",
  "MS Gothic",
  "MS Mincho",
  "MS Outlook",
  "MS PGothic",
  "MS PMincho",
  "MS Reference Sans Serif",
  "MS Reference Specialty",
  "MS Sans Serif 8,10,12,14,18,24",
  "MS Serif 8,10,12,14,18,24",
  "MS UI Gothic",
  "MT Extra",
  "MV Boli",
  "Myanmar Text",
  "Myanmar Text Bold",
  "Niagara Engraved",
  "Niagara Solid",
  "Nirmala Text",
  "Nirmala Text Bold",
  "Nirmala Text Semilight",
  "Nirmala UI",
  "Nirmala UI Bold",
  "Nirmala UI Semilight",
  "Noto Sans JP",
  "Noto Sans SC",
  "Noto Serif JP",
  "Noto Serif SC",
  "NSimSun",
  "OCR A Extended",
  "Old English Text MT",
  "Onyx",
  "Palace Script MT",
  "Palatino Linotype",
  "Palatino Linotype Bold",
  "Palatino Linotype Bold Italic",
  "Palatino Linotype Italic",
  "Papyrus",
  "Parchment",
  "Perpetua",
  "Perpetua Bold",
  "Perpetua Bold Italic",
  "Perpetua Italic",
  "Perpetua Titling MT Bold",
  "Perpetua Titling MT Light",
  "Playbill",
  "PMingLiU-ExtB",
  "Poor Richard",
  "Pristina",
  "Rage Italic",
  "Ravie",
  "Rockwell",
  "Rockwell Bold",
  "Rockwell Bold Italic",
  "Rockwell Condensed",
  "Rockwell Condensed Bold",
  "Rockwell Extra Bold",
  "Rockwell Italic",
  "ROGFonts-Regular",
  "Roman",
  "Sans Serif Collection",
  "Script",
  "Script MT Bold",
  "Segoe Fluent Icons",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Print Bold",
  "Segoe Script",
  "Segoe Script Bold",
  "Segoe UI",
  "Segoe UI Black",
  "Segoe UI Black Italic",
  "Segoe UI Bold",
  "Segoe UI Bold Italic",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Italic",
  "Segoe UI Light",
  "Segoe UI Light Italic",
  "Segoe UI Semibold",
  "Segoe UI Semibold Italic",
  "Segoe UI Semilight",
  "Segoe UI Semilight Italic",
  "Segoe UI Symbol",
  "Segoe UI Variable",
  "Showcard Gothic",
  "SimHei",
  "SimSun",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka Text",
  "Sitka Text Italic",
  "Small Fonts",
  "Snap ITC",
  "Stencil",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Tahoma Bold",
  "Tempus Sans ITC",
  "Times New Roman",
  "Times New Roman Bold",
  "Times New Roman Bold Italic",
  "Times New Roman Italic",
  "Trebuchet MS",
  "Trebuchet MS Bold",
  "Trebuchet MS Bold Italic",
  "Trebuchet MS Italic",
  "Tw Cen MT",
  "Tw Cen MT Bold",
  "Tw Cen MT Bold Italic",
  "Tw Cen MT Condensed",
  "Tw Cen MT Condensed Bold",
  "Tw Cen MT Condensed Extra Bold",
  "Tw Cen MT Italic",
  "UD Digi Kyokasho N",
  "UD Digi Kyokasho N Bold",
  "UD Digi Kyokasho NK",
  "UD Digi Kyokasho NK Bold",
  "UD Digi Kyokasho NP",
  "UD Digi Kyokasho NP Bold",
  "Verdana",
  "Verdana Bold",
  "Verdana Bold Italic",
  "Verdana Italic",
  "Viner Hand ITC",
  "Vivaldi Italic",
  "Vladimir Script",
  "Webdings",
  "Wide Latin",
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Yu Gothic Bold",
  "Yu Gothic Light",
  "Yu Gothic Medium",
  "Yu Gothic Regular",
  "Yu Gothic UI Bold",
  "Yu Gothic UI Light",
  "Yu Gothic UI Regular",
  "Yu Gothic UI Semibold",
  "Yu Gothic UI Semilight",
  "Yu Mincho",
  "Yu Mincho Demibold",
  "Yu Mincho Light",
  "方正舒体",
  "方正姚体",
  "华文彩云",
  "华文仿宋",
  "华文琥珀",
  "华文楷体",
  "华文隶书",
  "华文宋体",
  "华文细黑",
  "华文新魏",
  "华文行楷",
  "华文中宋",
  "隶书",
  "幼圆",
] as const;
