export const DEFAULT_MANGA_SYSML_FILES = [
  {
    path: "mangamaker-domain.sysml",
    content: [
      "package MangaMakerDomain {",
      "\tprivate import Parts::*;",
      "\tprivate import Requirements::*;",
      "",
      "\tpart def MangaProject :> Part {",
      "\t\tdoc",
      "\t\t/*",
      "\t\t * A MangaMaker comic treated as an engineered creative product.",
      "\t\t * Markdown documents and page assets are work products; pages, panels,",
      "\t\t * text, bubbles, and image resources are modeled as project parts.",
      "\t\t */",
      "\t}",
      "",
      "\tpart def ProductionDocument :> Part;",
      "\tpart def ComicPage :> Part;",
      "\tpart def StoryPanel :> Part;",
      "\tpart def ImageResource :> Part;",
      "\tpart def TextBlock :> Part;",
      "\tpart def SpeechBubble :> Part;",
      "\tpart def AgentRole :> Part;",
      "",
      "\trequirement def MangaRequirement :> RequirementCheck {",
      "\t\tsubject: MangaProject;",
      "\t}",
      "",
      "\trequirement def PageRequirement :> RequirementCheck {",
      "\t\tsubject: ComicPage;",
      "\t}",
      "",
      "\trequirement def PanelRequirement :> RequirementCheck {",
      "\t\tsubject: StoryPanel;",
      "\t}",
      "",
      "\trequirement def DocumentRequirement :> RequirementCheck {",
      "\t\tsubject: ProductionDocument;",
      "\t}",
      "}",
      "",
    ].join("\n"),
  },
  {
    path: "project-model.sysml",
    content: [
      "package MangaMakerProjectModel {",
      "\tprivate import Parts::*;",
      "\tprivate import Requirements::*;",
      "\tprivate import MangaMakerDomain::*;",
      "",
      "\tpart project: MangaProject {",
      "\t\tdoc",
      "\t\t/*",
      "\t\t * Replace this seed model with the project's MBSE model.",
      "\t\t * Keep page ids and document paths traceable to MangaMaker artifacts.",
      "\t\t */",
      "\t\tpart productionPlan: ProductionDocument;",
      "\t\tpart storyArchitecture: ProductionDocument;",
      "\t\tpart page001: ComicPage;",
      "\t}",
      "",
      "\trequirement def CreatorAuthorityRequirement :> MangaRequirement {",
      "\t\tdoc",
      "\t\t/* The human creator owns final creative direction and approval. */",
      "\t}",
      "",
      "\trequirement def TraceablePageRequirement :> PageRequirement {",
      "\t\tdoc",
      "\t\t/* Each production page should trace to intent, panel plan, text, and rendered review evidence. */",
      "\t}",
      "}",
      "",
    ].join("\n"),
  },
] as const;

export const createNonR18SampleSysmlFiles = () => [
  {
    path: "samples/clockwork-librarian.sysml",
    content: [
      "package ClockworkLibrarianSample {",
      "\tprivate import Parts::*;",
      "\tprivate import Requirements::*;",
      "\tprivate import MangaMakerDomain::*;",
      "",
      "\tpart clockworkLibrarian: MangaProject {",
      "\t\tdoc",
      "\t\t/*",
      "\t\t * Non-R18 test theme: a young inventor and a librarian recover a moon map",
      "\t\t * from a clockwork archive before dawn. The sample is used only for MBSE",
      "\t\t * workflow validation and contains no adult or explicit content.",
      "\t\t */",
      "\t\tpart producerBrief: ProductionDocument;",
      "\t\tpart directorModel: ProductionDocument;",
      "\t\tpart storyboardModel: ProductionDocument;",
      "\t\tpart page001: ComicPage;",
      "\t\tpart page002: ComicPage;",
      "\t\tpart page003: ComicPage;",
      "\t}",
      "",
      "\trequirement def SafeAudienceRequirement :> MangaRequirement {",
      "\t\tdoc",
      "\t\t/* The sample must remain non-R18 and suitable for general workflow testing. */",
      "\t}",
      "",
      "\trequirement def PageOneHookRequirement :> PageRequirement {",
      "\t\tdoc",
      "\t\t/* Page 1 establishes the locked archive, the map goal, and the visual clock motif. */",
      "\t}",
      "",
      "\trequirement def PageTwoEscalationRequirement :> PageRequirement {",
      "\t\tdoc",
      "\t\t/* Page 2 escalates through a mechanical obstacle and a character decision. */",
      "\t}",
      "",
      "\trequirement def PageThreeResolutionRequirement :> PageRequirement {",
      "\t\tdoc",
      "\t\t/* Page 3 resolves the mini-scene with the map found and a next-scene question. */",
      "\t}",
      "}",
      "",
    ].join("\n"),
  },
];
